Adding a section explaining OLE clients and servers behavior for Office version 2109 and newer.
MicrosoftDocs/office-developer-client-docs pull request #353
Opened 2021-11-19 18:47 UTC by JakubK44

The section discusses how Excel and PowerPoint handle DPI awareness compatibility when acting as OLE clients/servers, which changed in version 2109.

2021-11-19 18:49 UTC, opbld33 commented
Docs Build status updates of commit _[c4f0fbd](https://github.com/JakubK44/office-developer-client-docs/commits/c4f0fbd93d85ce567564573660f3729159fb9eb3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md](https://github.com/JakubK44/office-developer-client-docs/blob/master/docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md) | :warning:Warning | | [Details](#user-content-4a32e0c51f5308ce126fd17bfd9cf5d5-8651bd23)

<a id="4a32e0c51f5308ce126fd17bfd9cf5d5-8651bd23"></a>
### [docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md](https://github.com/JakubK44/office-developer-client-docs/blob/master/docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md)
 - **Line 553, Column 277**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 553, Column 413**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 34, Column 329**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 61, Column 174**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-setthreaddpiawarenesscontext' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 67, Column 439**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-setthreaddpiawarenesscontext' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 210, Column 51**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-setthreaddpiawarenesscontext' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 212, Column 293**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 235, Column 113**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getwindowdpiawarenesscontext' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 235, Column 414**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows#related-topics' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 238, Column 66**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/shellscalingapi/ne-shellscalingapi-process_dpi_awareness' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 238, Column 261**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/hidpi/dpi-awareness-context' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 238, Column 384**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getthreaddpiawarenesscontext' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 334, Column 161**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getwindowdpiawarenesscontext' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 336, Column 271**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/dotnet/framework/winforms/high-dpi-support-in-windows-forms' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 461, Column 333**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows#related-topics' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 463, Column 5**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/hidpi/wm-dpichanged' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 463, Column 191**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/winmsg/using-window-procedures' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 473, Column 154**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getdpiforwindow' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 532, Column 155**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getdpiforwindow' will be broken in isolated environments. Replace with a relative lin [...]

2021-11-19 21:37 UTC, JakubK44 commented
I'll fix the absolute paths issue throughout the page.

2021-11-19 21:53 UTC, opbld30 commented
Docs Build status updates of commit _[393c659](https://github.com/JakubK44/office-developer-client-docs/commits/393c659d42edde089bb657e4f66fc20e72f7e913)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md](https://github.com/JakubK44/office-developer-client-docs/blob/master/docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C1f41ed19-05df-4de3-6c32-a6870955a76e%5CPullRequest%5C202111192152234325-353%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T21%3A53%3A30Z&sr=b&sp=r&sig=kysYsUyD1vOLW%2BeCOLhWQGloD4GGgm5PvfOpKKtJD7M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/1f41ed19-05df-4de3-6c32-a6870955a76e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-21 18:00 UTC, opbld30 commented
Docs Build status updates of commit _[b71aeb4](https://github.com/JakubK44/office-developer-client-docs/commits/b71aeb41f6371a6582d9b0a07c85303b4fab6642)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md](https://github.com/JakubK44/office-developer-client-docs/blob/master/docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C21%5C1f41ed19-05df-4de3-6c32-a6870955a76e%5CPullRequest%5C202111211759226395-353%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-22T18%3A00%3A34Z&sr=b&sp=r&sig=uFKWyurvt%2FELNqvdS8rGmCbe9SIY%2BJ62CmOCsPOfi8k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/1f41ed19-05df-4de3-6c32-a6870955a76e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 19:46 UTC, davidchesnut requested changes
Looks good, a few comments and suggestions.

2021-12-06 19:46 UTC, davidchesnut commented on docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
> +Starting with version 2109 for Excel and PowerPoint, both applications allow in-place activation in Per Monitor DPI Aware modes when certain conditions are met. When in-place activated as OLE servers
Looks like some text is jumbled or something at "if it's compatible with [When using multiple displays]"

2021-12-06 19:46 UTC, davidchesnut commented on docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
> +- "Optimize for best appearance" will allow in-place activation if the window provided by the container is Per Monitor DPI Aware
```suggestion
- "Optimize for best appearance" will allow in-place activation if the window provided by the container is Per Monitor DPI Aware.
```

2021-12-06 19:46 UTC, davidchesnut commented on docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
> +- "Optimize for compatibility" will allow in-place activation if the window provided by the container is System DPI aware and system DPI matches between both the container application and the Office
```suggestion
- "Optimize for compatibility" will allow in-place activation if the window provided by the container is System DPI aware and both the container application and the Office application have the same system DPI.
```

2021-12-06 19:46 UTC, davidchesnut commented on docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
> +It means that DPI Unaware OLE containers will not be able to in-place activate either of the apps. The workaround is to change the DPI awareness of the container app to System DPI Aware (and use the
What does "It" refer to in the first sentence?

2021-12-06 19:46 UTC, davidchesnut commented on docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
> +When acting as an OLE container, both Excel and PowerPoint defer the DPI awareness compatibility check to the server and do not prevent in-place activation.
```suggestion
When acting as an OLE container, both Excel and PowerPoint defer to the server to check DPI awareness compatibility, and they do not prevent in-place activation.
```

2021-12-06 23:29 UTC, opbld30 commented
Docs Build status updates of commit _[38c8880](https://github.com/JakubK44/office-developer-client-docs/commits/38c88805e7c740466171756f0ba1720eb553df0a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-669143f4)

<a id="669143f4"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C1f41ed19-05df-4de3-6c32-a6870955a76e%5CPullRequest%5C202112062325234566-353%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T23%3A28%3A59Z&sr=b&sp=r&sig=bq9HhOonNvx54OZkeYKmQB53%2BROL0L7KSqMqKHTs92M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/1f41ed19-05df-4de3-6c32-a6870955a76e?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 23:32 UTC, davidchesnut commented on docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md
> +Starting with version 2109 for Excel and PowerPoint, both applications allow in-place activation in Per Monitor DPI Aware modes when certain conditions are met. When in-place activated as OLE servers
```suggestion
Starting with version 2109 for Excel and PowerPoint, both applications allow in-place activation in Per Monitor DPI Aware modes when certain conditions are met. When in-place activated as OLE servers, Office applications will check the `DPI_AWARENESS_CONTEXT` of the parent window provided by the container and allow in-place activation depending on which of the following [Office DPI display modes](https://support.microsoft.com/topic/office-support-for-high-definition-displays-6720ca0e-be59-41f6-b629-1369f549279d) is selected by the user:
```

2021-12-07 00:05 UTC, opbld33 commented
Docs Build status updates of commit _[7c36a87](https://github.com/JakubK44/office-developer-client-docs/commits/7c36a87ab45654d6a9313f3bc4365c08c4a616c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md](https://github.com/JakubK44/office-developer-client-docs/blob/master/docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C1f41ed19-05df-4de3-6c32-a6870955a76e%5CPullRequest%5C202112070003571771-353%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T00%3A05%3A04Z&sr=b&sp=r&sig=Sy9%2FNA81GsUZdd4gVrJjb0DCm2REPbFrQ9WmoYCXyXE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/1f41ed19-05df-4de3-6c32-a6870955a76e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 02:32 UTC, davidchesnut approved these changes
Looks great!

2021-12-07 02:32 UTC, merged